{
 "title": "Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"/public/img/logo-sqmss.jpg\" width=\"85\" height=\"85\"> </center>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "options": {
    "content": "               Monitoring Dashboard                      "
   }
  },
  {
   "title": "Count File",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_count{directory=\"/data/users/appuser/file\", instance=\"10.10.10.10:9200\", job=\"file_metrics_monitor\"}",
     "legendFormat": "Count Files"
    },
    {
     "expr": "last_mod_date{directory=\"/data/users/appuser/file\", instance=\"10.10.10.10:9200\", job=\"file_metrics_monitor\"}",
     "legendFormat": "Last Modified Date"
    }
   ]
  },
  {
   "title": "SFTP File List",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sftp_files{instance=\"10.10.10.10:9200\", job=\"file_metrics_monitor\"}",
     "legendFormat": "{{file}}"
    }
   ]
  },
  {
   "title": "Insert to Mongo DB Status",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "log_file_tail{file=\"/data/users/appuser/docker_mongo_insert.log\", instance=\"10.10.10.10:9200\", job=\"file_metrics_monitor\"}",
     "legendFormat": "Insert to Mongo"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "log_file_tail{file=\"/data/users/appuser/Job.log\", instance=\"10.10.10.10:9200\", job=\"file_metrics_monitor\"}",
     "legendFormat": "Insert to Mongo"
    }
   ]
  }
 ]
}